### ISSUE TITLE
При создании заказа не верно просчитывается маршрут

### ISSUE THREAD

**Issue by MazZilaaaa** [TransportSystems2/Backend#111]
<img width="787" alt="screenshot 2019-01-17 at 00 56 41" src="https://user-images.githubusercontent.com/2940479/51281355-30eb8700-19f3-11e9-893c-a6200ea547dc.png">
На изображении выше есть записи построенного маршрута (id = 2),

где:
1-гараж (Рыбинск)
34-место откуда забрать заказ (Рыбинск)
35-место куда отвезти груз (Ярославль)

В мобильном приложении было указано:
место погрузки = Рыбинск
место разгрузки = Ярославль

Судя по записям маршрут выглядит так: _гараж ->** место погрузки -> место разгрузки -> (место погрузки -> место разгрузки -> )** гараж_. Как видно, место погрузки и место разгрузки добавляется 2 раза (**выделено жирным**).

**Comment by fedorkin** [comment]
Не наблюдается.
